snake:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

  # Position Controllers ---------------------------------------

  joint0_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint0
    pid: {p: 50.0, i: 0.01, d: 10.0}

  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 50.0, i: 0.01, d: 10.0}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 50.0, i: 0.01, d: 10.0}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint3
    pid: {p: 50.0, i: 0.01, d: 10.0}

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint4
    pid: {p: 50.0, i: 0.01, d: 10.0}

  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint5
    pid: {p: 50.0, i: 0.01, d: 10.0}

  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint6
    pid: {p: 50.0, i: 0.01, d: 10.0}

  joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint7
    pid: {p: 50.0, i: 0.01, d: 10.0}

  joint8_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint8
    pid: {p: 50.0, i: 0.01, d: 10.0}

  joint9_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint9
    pid: {p: 50.0, i: 0.01, d: 10.0}

  joint10_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint10
    pid: {p: 50.0, i: 0.01, d: 10.0}

  joint11_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint11
    pid: {p: 50.0, i: 0.01, d: 10.0}

  joint12_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint12
    pid: {p: 50.0, i: 0.01, d: 10.0}

  joint13_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint13
    pid: {p: 50.0, i: 0.01, d: 10.0}

  joint14_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint14
    pid: {p: 50.0, i: 0.01, d: 10.0}

  joint15_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint15
    pid: {p: 50.0, i: 0.01, d: 10.0}

  joint16_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint16
    pid: {p: 50.0, i: 0.01, d: 10.0}

  joint17_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint17
    pid: {p: 50.0, i: 0.01, d: 10.0}

  joint18_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint18
    pid: {p: 50.0, i: 0.01, d: 10.0}

  joint19_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint19
    pid: {p: 50.0, i: 0.01, d: 10.0}

  joint20_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint20
    pid: {p: 50.0, i: 0.01, d: 10.0}

  joint21_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint21
    pid: {p: 50.0, i: 0.01, d: 10.0}

  joint22_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint22
    pid: {p: 50.0, i: 0.01, d: 10.0}

  joint23_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint23
    pid: {p: 50.0, i: 0.01, d: 10.0}

  joint24_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint24
    pid: {p: 50.0, i: 0.01, d: 10.0}

  joint25_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint25
    pid: {p: 50.0, i: 0.01, d: 10.0}

  joint26_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint26
    pid: {p: 50.0, i: 0.01, d: 10.0}

  joint27_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint27
    pid: {p: 50.0, i: 0.01, d: 10.0}

  joint28_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint28
    pid: {p: 50.0, i: 0.01, d: 10.0}

  joint29_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint29
    pid: {p: 50.0, i: 0.01, d: 10.0}


